container:
  postgres:
    image: postgres:16.3
    db-name: room_db
    username: postgres
    password: postgres
    init-script-path: "../local-start/init.sql"

liquibase:
  change-log-path: "file:../database/liquibase/changelog/changelog-master.yaml"
  schema: liquibase
  default-schema: public

spring:
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        show_sql: true
        format_sql: true
        generate_statistics: true
        cache:
          use_second_level_cache: false