spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      schema: ${DB_SCHEMA}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        show_sql: true
        format_sql: false
        generate_statistics: false
        cache:
          use_second_level_cache: false
  mvc:
    problemdetails:
      enabled: true